FISH = {
    "草灵鱼": {
        "name": "草灵鱼",
        "desc": "最常见的灵鱼，肉质鲜美，食之可微量恢复灵力。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 4,
    },
    "银鳞鱼": {
        "name": "银鳞鱼",
        "desc": "通体银鳞的灵鱼，鳞片可入药，是炼制低阶丹药的辅材。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 8,
    },
    "青玉鲤": {
        "name": "青玉鲤",
        "desc": "鳞片如青玉般温润的灵鲤，肉质含灵，食之可强身健体。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 12,
    },
    "墨甲龟": {
        "name": "墨甲龟",
        "desc": "背甲漆黑的灵龟，龟甲可入药延寿，亦可制作防御类符箓。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 18,
    },
    "金线鲈": {
        "name": "金线鲈",
        "desc": "体侧有金色纹路的灵鲈，内丹可提炼微量灵液，炼丹师常收购。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 15,
    },
    "寒潭冰鲤": {
        "name": "寒潭冰鲤",
        "desc": "寒潭深处的冰属灵鱼，血液极寒，是炼制冰属丹药的珍稀药引。",
        "type": "fish",
        "rarity": "稀有",
        "element": "水",
        "sell_price": 85,
    },
    "赤焰蛟鱼": {
        "name": "赤焰蛟鱼",
        "desc": "体内蕴含一丝蛟龙血脉的火属灵鱼，内丹价值不菲。",
        "type": "fish",
        "rarity": "稀有",
        "element": "火",
        "sell_price": 100,
    },
    "七彩灵虾": {
        "name": "七彩灵虾",
        "desc": "通体七彩流光的灵虾，虾壳可研磨为粉，是高阶丹药的稀有辅料。",
        "type": "fish",
        "rarity": "稀有",
        "element": None,
        "sell_price": 80,
    },
    "龙筋鳗": {
        "name": "龙筋鳗",
        "desc": "体内筋脉似龙筋的深水灵鳗，筋可制弓弦，肉可炼体魄丹。",
        "type": "fish",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 350,
    },
    "太古灵鳖": {
        "name": "太古灵鳖",
        "desc": "万年灵鳖，背甲刻有天然道纹，传说食其肉可增寿百年，甲可炼至宝。",
        "type": "fish",
        "rarity": "绝世",
        "element": None,
        "sell_price": 4000,
    },
    "灵溪鲫": {
        "name": "灵溪鲫",
        "desc": "灵溪中常见的小鲫，肉质细嫩，食之可微量补气。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 4,
    },
    "碧波鲢": {
        "name": "碧波鲢",
        "desc": "碧波潭所产灵鲢，鳞片可入药，是低阶丹药的常见辅材。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 6,
    },
    "青尾鲶": {
        "name": "青尾鲶",
        "desc": "青尾灵鲶，骨刺可磨成粉制符墨，符师常收。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 7,
    },
    "赤鳞鳅": {
        "name": "赤鳞鳅",
        "desc": "泥沼灵鳅，鳞泛赤色，炖汤可驱寒湿，低阶修士常用。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 5,
    },
    "银梭鱼": {
        "name": "银梭鱼",
        "desc": "身形如梭的灵鱼，游速极快，鱼骨可制简易飞针法器。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 9,
    },
    "墨鳞鲤": {
        "name": "墨鳞鲤",
        "desc": "通体墨色的灵鲤，胆可入药明目，鳞可炼低阶护甲片。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 10,
    },
    "金睛鲳": {
        "name": "金睛鲳",
        "desc": "眼泛金光的灵鲳，鱼眼可炼瞳术类丹药的辅料。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 11,
    },
    "玉带鳊": {
        "name": "玉带鳊",
        "desc": "体侧有一道玉色纹路的灵鳊，肉质含灵，食之可养神。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 12,
    },
    "石斑灵鱼": {
        "name": "石斑灵鱼",
        "desc": "礁石间生长的灵斑鱼，皮厚可制符皮，低阶炼器常用。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 8,
    },
    "桃花鳜": {
        "name": "桃花鳜",
        "desc": "春日桃花落水处所产灵鳜，肉质鲜美，可作宴席与补灵之用。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 14,
    },
    "雪鳞鲑": {
        "name": "雪鳞鲑",
        "desc": "寒域雪水中的灵鲑，鳞片如雪，可炼御寒丹药。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 13,
    },
    "乌江鲶": {
        "name": "乌江鲶",
        "desc": "大江深水中的灵鲶，须可制钓线、捆灵索的辅材。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 11,
    },
    "碧潭青鱼": {
        "name": "碧潭青鱼",
        "desc": "碧潭深处所产青鱼，肉质清甜，食之可宁心。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 9,
    },
    "赤尾金鲤": {
        "name": "赤尾金鲤",
        "desc": "尾鳍赤金的灵鲤，寓意吉祥，鳞片可炼低阶护身符。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 15,
    },
    "灵沼泥鳅": {
        "name": "灵沼泥鳅",
        "desc": "灵沼中的泥鳅，虽小却含土灵之气，可入土属丹方。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 6,
    },
    "月华鳝": {
        "name": "月华鳝",
        "desc": "月夜出没的灵鳝，肉质带一丝太阴之气，可炼阴属丹药。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 16,
    },
    "星子鱼": {
        "name": "星子鱼",
        "desc": "体表有星点斑纹的小灵鱼，传闻与星力有关，可作观星阵的祭品。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 10,
    },
    "龙须鲇": {
        "name": "龙须鲇",
        "desc": "长须如龙的灵鲇，须可制弦，是炼制灵琴的辅料。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 14,
    },
    "云梦银鱼": {
        "name": "云梦银鱼",
        "desc": "云梦大泽所产银鱼，通体透明含灵，可炼化形、幻术类丹药。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 18,
    },
    "玄水黑鲤": {
        "name": "玄水黑鲤",
        "desc": "玄水深处的黑鲤，鳞甲坚硬，可炼防御类符箓与甲片。",
        "type": "fish",
        "rarity": "普通",
        "element": None,
        "sell_price": 17,
    },
    "霜鳞鱼": {
        "name": "霜鳞鱼",
        "desc": "极寒水域的灵鱼，鳞带霜气，是炼制冰属丹药的稀有药引。",
        "type": "fish",
        "rarity": "稀有",
        "element": "水",
        "sell_price": 85,
    },
    "焰心鲤": {
        "name": "焰心鲤",
        "desc": "地火泉眼旁生长的灵鲤，体内蕴火灵，可炼火属丹药与法器。",
        "type": "fish",
        "rarity": "稀有",
        "element": "火",
        "sell_price": 95,
    },
    "雷纹鳗": {
        "name": "雷纹鳗",
        "desc": "雷雨过后出现的灵鳗，体表有雷纹，可炼雷属丹药。",
        "type": "fish",
        "rarity": "稀有",
        "element": "雷",
        "sell_price": 92,
    },
    "碧藻龙鱼": {
        "name": "碧藻龙鱼",
        "desc": "以灵藻为食的龙鱼，生机旺盛，可炼木属、疗伤类丹药。",
        "type": "fish",
        "rarity": "稀有",
        "element": "木",
        "sell_price": 88,
    },
    "沉渊石鱼": {
        "name": "沉渊石鱼",
        "desc": "渊底岩石般的灵鱼，厚重载物，可炼土属、防御类法宝辅材。",
        "type": "fish",
        "rarity": "稀有",
        "element": "土",
        "sell_price": 86,
    },
    "风梭鱼": {
        "name": "风梭鱼",
        "desc": "御风而行的灵鱼，骨轻如羽，可炼飞行法器与风属法宝。",
        "type": "fish",
        "rarity": "稀有",
        "element": None,
        "sell_price": 90,
    },
    "鬼面鳐": {
        "name": "鬼面鳐",
        "desc": "幽冥水域所产灵鳐，背纹如鬼面，可炼鬼道、阴属丹药。",
        "type": "fish",
        "rarity": "稀有",
        "element": None,
        "sell_price": 82,
    },
    "蛟鳞鱼": {
        "name": "蛟鳞鱼",
        "desc": "含有一丝蛟龙血脉的灵鱼，鳞片可炼护甲，血可炼体。",
        "type": "fish",
        "rarity": "稀有",
        "element": None,
        "sell_price": 98,
    },
    "七彩鲛": {
        "name": "七彩鲛",
        "desc": "鲛人海域边缘的灵鲛，泪可化珠，鳞可炼幻术类法器。",
        "type": "fish",
        "rarity": "稀有",
        "element": None,
        "sell_price": 100,
    },
    "玄冰鳕": {
        "name": "玄冰鳕",
        "desc": "玄冰层下所产灵鳕，血肉皆寒，是冰属修士的炼器药引。",
        "type": "fish",
        "rarity": "稀有",
        "element": "水",
        "sell_price": 93,
    },
    "赤焰虾": {
        "name": "赤焰虾",
        "desc": "地火脉附近的热泉中所产灵虾，通体赤红，可炼火属丹与器。",
        "type": "fish",
        "rarity": "稀有",
        "element": "火",
        "sell_price": 94,
    },
    "星罗鱼": {
        "name": "星罗鱼",
        "desc": "背纹如星图的灵鱼，可炼观星、推演类法阵的祭品与辅材。",
        "type": "fish",
        "rarity": "稀有",
        "element": None,
        "sell_price": 97,
    },
    "龙子鲤": {
        "name": "龙子鲤",
        "desc": "传说跃过龙门的灵鲤所留血脉，内丹珍贵，可炼化龙类丹药。",
        "type": "fish",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 250,
    },
    "凤尾灵鱼": {
        "name": "凤尾灵鱼",
        "desc": "尾鳍如凤尾的灵鱼，蕴含一丝涅槃之意，可炼重生类丹药。",
        "type": "fish",
        "rarity": "珍贵",
        "element": "火",
        "sell_price": 300,
    },
    "玄武幼龟": {
        "name": "玄武幼龟",
        "desc": "带有一丝玄武血脉的灵龟，甲可炼至强防御法宝，血可炼体。",
        "type": "fish",
        "rarity": "珍贵",
        "element": "土",
        "sell_price": 360,
    },
    "鲲鹏鳞鱼": {
        "name": "鲲鹏鳞鱼",
        "desc": "北冥边缘所产的巨鱼后裔，鳞片可炼空间与飞行类至宝。",
        "type": "fish",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 420,
    },
    "太古龙鲤": {
        "name": "太古龙鲤",
        "desc": "太古龙族与灵鲤血脉交融所生，炼化其内丹可悟一丝真龙之道。",
        "type": "fish",
        "rarity": "绝世",
        "element": None,
        "sell_price": 2800,
    },
    "瑶池金莲鱼": {
        "name": "瑶池金莲鱼",
        "desc": "瑶池金莲下所养灵鱼，食金莲长大，食之可脱胎换骨、延寿千年。",
        "type": "fish",
        "rarity": "绝世",
        "element": None,
        "sell_price": 3500,
    },
    "黄泉摆渡鱼": {
        "name": "黄泉摆渡鱼",
        "desc": "黄泉河中专司摆渡的灵鱼，炼化可得一缕轮回真意。",
        "type": "fish",
        "rarity": "绝世",
        "element": None,
        "sell_price": 4200,
    },
    "混沌鲲苗": {
        "name": "混沌鲲苗",
        "desc": "混沌海中诞生的鲲苗，传说养大可化鹏，炼化可触混沌大道。",
        "type": "fish",
        "rarity": "绝世",
        "element": None,
        "sell_price": 5000,
    },
}
