HERBS = {
    "灵芝草": {
        "name": "灵芝草",
        "desc": "最常见的灵药，可入低阶丹方，炼气期修士常用。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 5,
    },
    "九节菖蒲": {
        "name": "九节菖蒲",
        "desc": "生于溪畔的灵草，可安神定魄，是炼制培元丹的基础药材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 8,
    },
    "血藤草": {
        "name": "血藤草",
        "desc": "茎叶泛红的灵藤，可活血化瘀，是疗伤丹药的常见辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 10,
    },
    "紫苏灵草": {
        "name": "紫苏灵草",
        "desc": "叶片泛紫的灵草，可解百毒，是炼制解毒丹的主药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 12,
    },
    "碧灵花": {
        "name": "碧灵花",
        "desc": "四季常开的碧色灵花，花蜜可入丹，是聚灵丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 15,
    },
    "寒玉藤": {
        "name": "寒玉藤",
        "desc": "冰属灵藤，汁液冰寒，是炼制冰属丹药的稀有药引。",
        "type": "herb",
        "rarity": "稀有",
        "element": "水",
        "sell_price": 85,
    },
    "赤焰莲": {
        "name": "赤焰莲",
        "desc": "生于火山口的灵莲，花瓣灼热，可炼火属丹药与淬体丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "火",
        "sell_price": 95,
    },
    "雷灵芝": {
        "name": "雷灵芝",
        "desc": "雷击之地生长的灵芝，蕴含雷霆之力，可炼渡劫丹的辅药。",
        "type": "herb",
        "rarity": "稀有",
        "element": "雷",
        "sell_price": 90,
    },
    "九转还魂草": {
        "name": "九转还魂草",
        "desc": "传说可起死回生的珍稀灵草，是炼制续命丹的核心主药。",
        "type": "herb",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 300,
    },
    "太岁灵芝": {
        "name": "太岁灵芝",
        "desc": "万年太岁上生长的灵芝，蕴含造化之力，乃炼制仙丹的无上药引。",
        "type": "herb",
        "rarity": "绝世",
        "element": None,
        "sell_price": 3000,
    },
    "青蒿灵草": {
        "name": "青蒿灵草",
        "desc": "山野常见的灵蒿，可清热退邪，是炼制辟邪丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 5,
    },
    "白芷根": {
        "name": "白芷根",
        "desc": "灵芷之根，香气醒神，可入安神丹与定魄丹方。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 7,
    },
    "丹参灵草": {
        "name": "丹参灵草",
        "desc": "根茎赤红如丹，可活血养心，是疗伤丹与护心丹的常见主药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 9,
    },
    "茯苓灵块": {
        "name": "茯苓灵块",
        "desc": "灵茯苓结块，可健脾宁心，是培元丹与固本丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 8,
    },
    "甘草灵根": {
        "name": "甘草灵根",
        "desc": "灵甘草之根，可调和诸药、缓和其他药性，丹方中常用作和药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 6,
    },
    "金银灵花": {
        "name": "金银灵花",
        "desc": "一株双色，金白相间，可清热解毒，是解毒丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 10,
    },
    "何首乌藤": {
        "name": "何首乌藤",
        "desc": "灵何首乌的藤蔓，可乌发固本，是延寿类丹方的辅药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 11,
    },
    "当归灵草": {
        "name": "当归灵草",
        "desc": "补血养气之灵草，可入疗伤丹与补气丹方。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 9,
    },
    "川芎灵根": {
        "name": "川芎灵根",
        "desc": "灵川芎之根，可行气活血，是化瘀丹与疗伤丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 8,
    },
    "黄芪灵草": {
        "name": "黄芪灵草",
        "desc": "可补气固表，是培元丹与筑基丹方的常见辅药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 10,
    },
    "枸杞灵果": {
        "name": "枸杞灵果",
        "desc": "灵枸杞所结果实，可明目养肝，是养神丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 7,
    },
    "五味灵子": {
        "name": "五味灵子",
        "desc": "灵五味子之果，可敛肺滋肾，是固本丹与养元丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 12,
    },
    "决明灵草": {
        "name": "决明灵草",
        "desc": "可清肝明目，是炼瞳术类丹药与养神丹的辅药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 8,
    },
    "远志灵根": {
        "name": "远志灵根",
        "desc": "可安神益智，是定魄丹与悟道丹低阶版本的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 11,
    },
    "麦冬灵草": {
        "name": "麦冬灵草",
        "desc": "可养阴润肺，是滋阴丹与疗伤丹的常见辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 9,
    },
    "天麻灵块": {
        "name": "天麻灵块",
        "desc": "灵天麻结块，可息风定惊，是安神丹与镇魂丹的辅药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 13,
    },
    "杜仲灵皮": {
        "name": "杜仲灵皮",
        "desc": "灵杜仲之皮，可强筋骨，是淬体丹与锻骨丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 12,
    },
    "三七灵根": {
        "name": "三七灵根",
        "desc": "可止血化瘀，是疗伤丹与金创丹的主药之一。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 14,
    },
    "石斛灵茎": {
        "name": "石斛灵茎",
        "desc": "灵石斛之茎，可滋阴清热，是养元丹与延寿丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 15,
    },
    "雪莲灵瓣": {
        "name": "雪莲灵瓣",
        "desc": "高山雪莲之瓣，可驱寒温经，是御寒丹与温脉丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 14,
    },
    "霜华草": {
        "name": "霜华草",
        "desc": "生于极寒之地的灵草，叶带霜纹，可炼冰属丹药与御寒丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "水",
        "sell_price": 88,
    },
    "地火芝": {
        "name": "地火芝",
        "desc": "地脉火口旁生长的灵芝，蕴含地火之气，可炼火属丹药与淬体丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "火",
        "sell_price": 92,
    },
    "雷鸣花": {
        "name": "雷鸣花",
        "desc": "雷雨过后才开的灵花，花瓣带雷纹，可炼雷属丹药与破障丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "雷",
        "sell_price": 90,
    },
    "碧血藤": {
        "name": "碧血藤",
        "desc": "古战场遗址所生灵藤，藤心泛红，蕴含生机与血煞，可炼木属与疗伤类丹药。",
        "type": "herb",
        "rarity": "稀有",
        "element": "木",
        "sell_price": 87,
    },
    "玄黄土精": {
        "name": "玄黄土精",
        "desc": "地脉深处凝聚的土属灵精，可炼土属丹药与固本丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "土",
        "sell_price": 86,
    },
    "冰心莲": {
        "name": "冰心莲",
        "desc": "寒潭中心所生灵莲，莲心蕴寒，可炼冰属丹药与清心丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "水",
        "sell_price": 91,
    },
    "赤阳果": {
        "name": "赤阳果",
        "desc": "烈日下生长的灵果，果肉灼热，可炼火属丹药与纯阳丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "火",
        "sell_price": 93,
    },
    "风纹叶": {
        "name": "风纹叶",
        "desc": "高崖风口所长灵木之叶，叶脉如风纹，可炼轻身丹与风属辅药。",
        "type": "herb",
        "rarity": "稀有",
        "element": None,
        "sell_price": 89,
    },
    "月华露草": {
        "name": "月华露草",
        "desc": "只在月夜凝结露珠的灵草，可炼太阴类丹药与养神丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": None,
        "sell_price": 94,
    },
    "龙涎草": {
        "name": "龙涎草",
        "desc": "传说沾过真龙涎液的灵草，可炼化龙类丹药与高阶淬体丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": None,
        "sell_price": 95,
    },
    "凤尾蕨": {
        "name": "凤尾蕨",
        "desc": "形如凤尾的灵蕨，蕴含一丝涅槃之意，可炼重生类丹药的辅药。",
        "type": "herb",
        "rarity": "稀有",
        "element": "火",
        "sell_price": 94,
    },
    "七星海棠": {
        "name": "七星海棠",
        "desc": "叶有七星的灵海棠，可炼毒丹亦可入解毒丹，全看丹师手法。",
        "type": "herb",
        "rarity": "稀有",
        "element": None,
        "sell_price": 88,
    },
    "千年参须": {
        "name": "千年参须",
        "desc": "千年灵参的根须，可大补元气、延年益寿，是续命丹与延寿丹的核心辅药。",
        "type": "herb",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 320,
    },
    "幽冥还阳草": {
        "name": "幽冥还阳草",
        "desc": "生于阴阳交界处的灵草，可吊命还阳，是炼制还魂丹的主药。",
        "type": "herb",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 380,
    },
    "造化青莲": {
        "name": "造化青莲",
        "desc": "蕴含一丝造化之力的灵莲，可炼突破丹与洗髓丹，极为难得。",
        "type": "herb",
        "rarity": "珍贵",
        "element": "木",
        "sell_price": 350,
    },
    "涅槃凤翎花": {
        "name": "涅槃凤翎花",
        "desc": "传说凤凰涅槃时落下的翎羽所化灵花，可炼重生类与破境丹。",
        "type": "herb",
        "rarity": "珍贵",
        "element": "火",
        "sell_price": 400,
    },
    "混沌青莲": {
        "name": "混沌青莲",
        "desc": "混沌初开时遗留的灵莲种子所生，蕴含混沌之力，乃炼制仙丹的至宝。",
        "type": "herb",
        "rarity": "绝世",
        "element": None,
        "sell_price": 4500,
    },
    "不死药残根": {
        "name": "不死药残根",
        "desc": "传说中不死药的残根，服之可延寿千年，是炼制长生丹的无上主药。",
        "type": "herb",
        "rarity": "绝世",
        "element": None,
        "sell_price": 5000,
    },
    "菩提悟道叶": {
        "name": "菩提悟道叶",
        "desc": "灵山菩提树所落之叶，可助悟道破障，乃炼制悟道仙丹的至宝。",
        "type": "herb",
        "rarity": "绝世",
        "element": None,
        "sell_price": 3800,
    },
    "鸿蒙紫气芝": {
        "name": "鸿蒙紫气芝",
        "desc": "鸿蒙初判时一缕紫气所化灵芝，蕴含天道至理，可炼化神丹与飞升丹。",
        "type": "herb",
        "rarity": "绝世",
        "element": None,
        "sell_price": 4200,
    },
    "薄荷灵叶": {
        "name": "薄荷灵叶",
        "desc": "清凉醒神的灵薄荷叶，可入清心丹与解毒丹方。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 5,
    },
    "艾草灵蒿": {
        "name": "艾草灵蒿",
        "desc": "可驱邪温经，是辟邪丹与温脉丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 6,
    },
    "苍术灵根": {
        "name": "苍术灵根",
        "desc": "可健脾燥湿，是培元丹与化湿丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 7,
    },
    "防风灵草": {
        "name": "防风灵草",
        "desc": "可祛风解表，是御邪丹与护体丹的常见辅药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 8,
    },
    "荆芥灵叶": {
        "name": "荆芥灵叶",
        "desc": "可散风透疹，是解毒丹与清心丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 6,
    },
    "柴胡灵根": {
        "name": "柴胡灵根",
        "desc": "可疏肝解郁，是安神丹与定魄丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 9,
    },
    "黄芩灵草": {
        "name": "黄芩灵草",
        "desc": "可清热燥湿，是解毒丹与泻火丹的常见主药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 10,
    },
    "黄连灵根": {
        "name": "黄连灵根",
        "desc": "苦寒清热，可入解毒丹与清心丹方。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 11,
    },
    "栀子灵果": {
        "name": "栀子灵果",
        "desc": "可泻火除烦，是清心丹与安神丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 8,
    },
    "连翘灵花": {
        "name": "连翘灵花",
        "desc": "可清热解毒，是解毒丹与疗伤丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 9,
    },
    "板蓝灵根": {
        "name": "板蓝灵根",
        "desc": "可凉血解毒，是解毒丹与辟邪丹的辅药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 7,
    },
    "蒲公英灵草": {
        "name": "蒲公英灵草",
        "desc": "可清热消肿，是疗伤丹与解毒丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 5,
    },
    "夏枯灵穗": {
        "name": "夏枯灵穗",
        "desc": "可清肝散结，是养神丹与明目丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 10,
    },
    "芦根灵茎": {
        "name": "芦根灵茎",
        "desc": "可生津止渴，是养元丹与补气丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 6,
    },
    "竹叶灵心": {
        "name": "竹叶灵心",
        "desc": "可清心除烦，是清心丹与定魄丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 8,
    },
    "桑叶灵片": {
        "name": "桑叶灵片",
        "desc": "可疏风清热，是养神丹与明目丹的辅药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 7,
    },
    "菊花灵瓣": {
        "name": "菊花灵瓣",
        "desc": "可平肝明目，是养神丹与清心丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 9,
    },
    "桑寄生藤": {
        "name": "桑寄生藤",
        "desc": "可补肝肾、强筋骨，是淬体丹与养元丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 12,
    },
    "仙茅灵根": {
        "name": "仙茅灵根",
        "desc": "可温肾壮阳，是筑基丹与淬体丹的辅药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 13,
    },
    "巴戟灵根": {
        "name": "巴戟灵根",
        "desc": "可补肾助阳，是固本丹与培元丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 14,
    },
    "玄冰草": {
        "name": "玄冰草",
        "desc": "生于玄冰窟的灵草，叶带冰纹，可炼冰属丹药与镇心丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "水",
        "sell_price": 87,
    },
    "地炎花": {
        "name": "地炎花",
        "desc": "地火脉旁所生灵花，花瓣灼热，可炼火属丹药与淬体丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "火",
        "sell_price": 91,
    },
    "雷击藤": {
        "name": "雷击藤",
        "desc": "遭雷击而不死的灵藤，藤心蕴雷力，可炼雷属丹药与破障丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "雷",
        "sell_price": 89,
    },
    "青木灵心": {
        "name": "青木灵心",
        "desc": "万年灵木树心所取，蕴含蓬勃生机，可炼木属丹药与疗伤丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "木",
        "sell_price": 88,
    },
    "厚土灵根": {
        "name": "厚土灵根",
        "desc": "地脉深处灵根，沉稳厚重，可炼土属丹药与固本丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "土",
        "sell_price": 86,
    },
    "霜蕊莲": {
        "name": "霜蕊莲",
        "desc": "雪山灵莲，花蕊凝霜，可炼冰属丹药与延寿丹辅药。",
        "type": "herb",
        "rarity": "稀有",
        "element": "水",
        "sell_price": 90,
    },
    "赤霞芝": {
        "name": "赤霞芝",
        "desc": "朝霞映照处所生灵芝，蕴含火灵，可炼火属丹药与纯阳丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "火",
        "sell_price": 93,
    },
    "紫雷果": {
        "name": "紫雷果",
        "desc": "雷云下所生灵果，果皮带雷纹，可炼雷属丹药与破境丹辅药。",
        "type": "herb",
        "rarity": "稀有",
        "element": "雷",
        "sell_price": 92,
    },
    "碧落藤": {
        "name": "碧落藤",
        "desc": "传说自碧落天界坠落的灵藤残枝，可炼高阶养元丹与悟道丹辅药。",
        "type": "herb",
        "rarity": "稀有",
        "element": None,
        "sell_price": 95,
    },
    "黄泉引": {
        "name": "黄泉引",
        "desc": "幽冥地界边缘所生灵草，可炼阴属丹药与还魂丹辅药。",
        "type": "herb",
        "rarity": "稀有",
        "element": None,
        "sell_price": 88,
    },
    "星辰草": {
        "name": "星辰草",
        "desc": "吸收星力生长的灵草，叶有星点，可炼观星丹与推演类丹药。",
        "type": "herb",
        "rarity": "稀有",
        "element": None,
        "sell_price": 94,
    },
    "玉髓芝": {
        "name": "玉髓芝",
        "desc": "玉脉旁所生灵芝，芝体如髓，可炼固本丹与筑基丹，极为难得。",
        "type": "herb",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 280,
    },
    "九幽还魂藤": {
        "name": "九幽还魂藤",
        "desc": "九幽深处所生灵藤，可吊命还魂，是还魂丹与续命丹的核心主药。",
        "type": "herb",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 360,
    },
    "太阳精草": {
        "name": "太阳精草",
        "desc": "太阳精火淬炼之地所生灵草，可炼至阳丹与破障丹。",
        "type": "herb",
        "rarity": "珍贵",
        "element": "火",
        "sell_price": 390,
    },
    "太阴寒芝": {
        "name": "太阴寒芝",
        "desc": "太阴之精凝结处所生灵芝，可炼至阴丹与养神丹。",
        "type": "herb",
        "rarity": "珍贵",
        "element": "水",
        "sell_price": 370,
    },
    "世界树嫩芽": {
        "name": "世界树嫩芽",
        "desc": "上古世界树崩毁后残存嫩芽，蕴含一方世界雏形之力，可炼飞升丹。",
        "type": "herb",
        "rarity": "绝世",
        "element": None,
        "sell_price": 4800,
    },
    "开天莲": {
        "name": "开天莲",
        "desc": "传说开天辟地时遗留的灵莲，蕴含创世之力，乃炼制仙丹的至宝。",
        "type": "herb",
        "rarity": "绝世",
        "element": None,
        "sell_price": 5000,
    },
    "造化玉露": {
        "name": "造化玉露",
        "desc": "造化玉碟所凝露珠，一滴可化腐朽为神奇，是炼制仙丹的无上药引。",
        "type": "herb",
        "rarity": "绝世",
        "element": None,
        "sell_price": 4600,
    },
    "天道碎片": {
        "name": "天道碎片",
        "desc": "天道崩碎时坠落的规则碎片所化灵物，可炼悟道仙丹与化神丹。",
        "type": "herb",
        "rarity": "绝世",
        "element": None,
        "sell_price": 5000,
    },
    "佩兰灵草": {
        "name": "佩兰灵草",
        "desc": "可化湿醒脾，是培元丹与化湿丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 6,
    },
    "藿香灵叶": {
        "name": "藿香灵叶",
        "desc": "可解暑化湿，是解毒丹与清心丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 7,
    },
    "砂仁灵果": {
        "name": "砂仁灵果",
        "desc": "可温脾开胃，是培元丹与筑基丹的辅药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 8,
    },
    "白豆蔻灵实": {
        "name": "白豆蔻灵实",
        "desc": "可化湿行气，是固本丹与养元丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 9,
    },
    "丁香灵蕾": {
        "name": "丁香灵蕾",
        "desc": "可温中降逆，是淬体丹与温脉丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 10,
    },
    "小茴灵籽": {
        "name": "小茴灵籽",
        "desc": "可散寒止痛，是疗伤丹与温经丹的辅药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 7,
    },
    "肉桂灵皮": {
        "name": "肉桂灵皮",
        "desc": "可补火助阳，是筑基丹与淬体丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 11,
    },
    "附子灵根": {
        "name": "附子灵根",
        "desc": "可回阳救逆，是续命丹与护心丹的辅材，用量需慎。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 13,
    },
    "干姜灵块": {
        "name": "干姜灵块",
        "desc": "可温中散寒，是温脉丹与培元丹的辅药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 8,
    },
    "吴茱萸灵果": {
        "name": "吴茱萸灵果",
        "desc": "可散寒止痛，是疗伤丹与温经丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 12,
    },
    "花椒灵实": {
        "name": "花椒灵实",
        "desc": "可温中止痛，是淬体丹与化瘀丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 9,
    },
    "高良姜灵根": {
        "name": "高良姜灵根",
        "desc": "可散寒止痛，是温脉丹与疗伤丹的辅药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 10,
    },
    "寒水藤": {
        "name": "寒水藤",
        "desc": "寒潭边所生灵藤，藤身沁凉，可炼冰属丹药与清心丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "水",
        "sell_price": 85,
    },
    "凝冰花": {
        "name": "凝冰花",
        "desc": "冰雪秘境所生灵花，花瓣凝霜，可炼冰属丹药与御寒丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "水",
        "sell_price": 88,
    },
    "玄阴草": {
        "name": "玄阴草",
        "desc": "极阴之地所生灵草，可炼太阴类丹药与养神丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "水",
        "sell_price": 90,
    },
    "碧波莲心": {
        "name": "碧波莲心",
        "desc": "灵湖深处灵莲之芯，水灵充沛，可炼水属丹药与养元丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "水",
        "sell_price": 91,
    },
    "焰心草": {
        "name": "焰心草",
        "desc": "地火脉心所生灵草，叶脉灼红，可炼火属丹药与淬体丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "火",
        "sell_price": 89,
    },
    "赤炼藤": {
        "name": "赤炼藤",
        "desc": "火山口所生灵藤，藤身灼热，可炼火属丹药与纯阳丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "火",
        "sell_price": 92,
    },
    "炎阳果": {
        "name": "炎阳果",
        "desc": "烈日曝晒处所生灵果，果肉炽热，可炼火属丹药与破障丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "火",
        "sell_price": 94,
    },
    "朱砂灵叶": {
        "name": "朱砂灵叶",
        "desc": "地火淬炼之地产朱砂灵叶，可炼火属丹药与镇魂丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "火",
        "sell_price": 93,
    },
    "雷纹草": {
        "name": "雷纹草",
        "desc": "雷劫落地处所生灵草，叶带雷纹，可炼雷属丹药与破障丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "雷",
        "sell_price": 87,
    },
    "紫电芝": {
        "name": "紫电芝",
        "desc": "雷云下所生灵芝，芝盖蕴雷力，可炼雷属丹药与渡劫丹辅药。",
        "type": "herb",
        "rarity": "稀有",
        "element": "雷",
        "sell_price": 90,
    },
    "惊雷藤": {
        "name": "惊雷藤",
        "desc": "常年遭雷击的山崖所生灵藤，可炼雷属丹药与破境丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "雷",
        "sell_price": 93,
    },
    "青藤灵心": {
        "name": "青藤灵心",
        "desc": "万年灵藤所取藤心，生机勃勃，可炼木属丹药与疗伤丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "木",
        "sell_price": 86,
    },
    "碧叶灵果": {
        "name": "碧叶灵果",
        "desc": "灵木所结碧色灵果，蕴含木灵，可炼木属丹药与养元丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "木",
        "sell_price": 89,
    },
    "长春藤": {
        "name": "长春藤",
        "desc": "四季常青的灵藤，生机不绝，可炼木属丹药与延寿丹辅药。",
        "type": "herb",
        "rarity": "稀有",
        "element": "木",
        "sell_price": 91,
    },
    "地脉根": {
        "name": "地脉根",
        "desc": "地脉裸露处所生灵根，厚重载物，可炼土属丹药与固本丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "土",
        "sell_price": 85,
    },
    "黄精灵块": {
        "name": "黄精灵块",
        "desc": "地脉深处灵黄精结块，土灵充沛，可炼土属丹药与培元丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "土",
        "sell_price": 88,
    },
    "山岩芝": {
        "name": "山岩芝",
        "desc": "灵山岩缝所生灵芝，吸纳地气，可炼土属丹药与淬体丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "土",
        "sell_price": 90,
    },
    "罡风草": {
        "name": "罡风草",
        "desc": "高崖罡风处所生灵草，叶脉如风纹，可炼轻身丹与飞行类丹药辅药。",
        "type": "herb",
        "rarity": "稀有",
        "element": None,
        "sell_price": 92,
    },
    "星辉露": {
        "name": "星辉露",
        "desc": "星力凝结的灵露，可炼观星丹与推演类丹药。",
        "type": "herb",
        "rarity": "稀有",
        "element": None,
        "sell_price": 95,
    },
    "碧海潮生草": {
        "name": "碧海潮生草",
        "desc": "深海灵脉边缘所生灵草，水灵与生机并具，可炼高阶养元丹与续命丹辅药。",
        "type": "herb",
        "rarity": "珍贵",
        "element": "水",
        "sell_price": 340,
    },
    "离火精芝": {
        "name": "离火精芝",
        "desc": "离火之精淬炼处所生灵芝，可炼至阳丹与涅槃类丹药。",
        "type": "herb",
        "rarity": "珍贵",
        "element": "火",
        "sell_price": 380,
    },
    "天雷劫莲": {
        "name": "天雷劫莲",
        "desc": "渡劫之地雷力凝结所生灵莲，可炼渡劫丹与破境丹。",
        "type": "herb",
        "rarity": "珍贵",
        "element": "雷",
        "sell_price": 370,
    },
    "建木灵芽": {
        "name": "建木灵芽",
        "desc": "上古建木残存灵芽，蕴含沟通天地之力，可炼飞升丹与悟道丹。",
        "type": "herb",
        "rarity": "珍贵",
        "element": "木",
        "sell_price": 390,
    },
    "太阴玄冰莲": {
        "name": "太阴玄冰莲",
        "desc": "太阴与玄冰交汇处所生灵莲，可炼至阴仙丹与长生丹辅药。",
        "type": "herb",
        "rarity": "绝世",
        "element": "水",
        "sell_price": 4500,
    },
    "太阳真火芝": {
        "name": "太阳真火芝",
        "desc": "太阳真火淬炼之地所生灵芝，可炼至阳仙丹与飞升丹。",
        "type": "herb",
        "rarity": "绝世",
        "element": "火",
        "sell_price": 4700,
    },
    "九天雷劫果": {
        "name": "九天雷劫果",
        "desc": "九天雷劫劈中所生灵树所结果实，蕴含天劫之力，可炼渡劫仙丹。",
        "type": "herb",
        "rarity": "绝世",
        "element": "雷",
        "sell_price": 4600,
    },
    "五行造化根": {
        "name": "五行造化根",
        "desc": "五行齐聚之地所生灵根，蕴含五行造化之力，乃炼制仙丹的无上主药。",
        "type": "herb",
        "rarity": "绝世",
        "element": None,
        "sell_price": 5000,
    },
    "苏叶灵草": {
        "name": "苏叶灵草",
        "desc": "可解表散寒，是御邪丹与温经丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 5,
    },
    "生姜灵块": {
        "name": "生姜灵块",
        "desc": "可温中止呕，是培元丹与温脉丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 6,
    },
    "葱白灵茎": {
        "name": "葱白灵茎",
        "desc": "可发汗解表，是解毒丹与清心丹的辅药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 5,
    },
    "荆芥穗": {
        "name": "荆芥穗",
        "desc": "可祛风解表，是护体丹与辟邪丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 7,
    },
    "牛蒡灵子": {
        "name": "牛蒡灵子",
        "desc": "可疏散风热，是解毒丹与疗伤丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 8,
    },
    "蝉蜕灵壳": {
        "name": "蝉蜕灵壳",
        "desc": "灵蝉所蜕之壳，可疏风透疹，是清心丹的辅药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 9,
    },
    "升麻灵根": {
        "name": "升麻灵根",
        "desc": "可升举阳气，是培元丹与固本丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 10,
    },
    "葛根灵块": {
        "name": "葛根灵块",
        "desc": "可生津止渴，是养元丹与补气丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 8,
    },
    "知母灵根": {
        "name": "知母灵根",
        "desc": "可清热泻火，是清心丹与安神丹的辅药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 11,
    },
    "芦根灵须": {
        "name": "芦根灵须",
        "desc": "灵芦根之须，可生津除烦，是养元丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 7,
    },
    "天花粉灵块": {
        "name": "天花粉灵块",
        "desc": "可清热生津，是解毒丹与养元丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 9,
    },
    "淡竹灵叶": {
        "name": "淡竹灵叶",
        "desc": "可清热除烦，是清心丹与定魄丹的辅药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 8,
    },
    "夏枯灵草": {
        "name": "夏枯灵草",
        "desc": "可清肝明目，是养神丹与明目丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 10,
    },
    "谷精灵草": {
        "name": "谷精灵草",
        "desc": "可明目退翳，是炼瞳术类丹药的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 11,
    },
    "密蒙灵花": {
        "name": "密蒙灵花",
        "desc": "可清热明目，是养神丹的辅药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 12,
    },
    "青葙灵子": {
        "name": "青葙灵子",
        "desc": "可清肝明目，是明目丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 9,
    },
    "木贼灵草": {
        "name": "木贼灵草",
        "desc": "可疏风明目，是养神丹与清心丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 7,
    },
    "蔓荆灵子": {
        "name": "蔓荆灵子",
        "desc": "可疏散风热，是清心丹的辅药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 10,
    },
    "桑白灵皮": {
        "name": "桑白灵皮",
        "desc": "可泻肺平喘，是疗伤丹与养元丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 11,
    },
    "枇杷灵叶": {
        "name": "枇杷灵叶",
        "desc": "可清肺止咳，是养元丹与疗伤丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 9,
    },
    "马兜灵铃": {
        "name": "马兜灵铃",
        "desc": "可清肺降气，是解毒丹的辅药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 13,
    },
    "百部灵根": {
        "name": "百部灵根",
        "desc": "可润肺止咳，是养元丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 8,
    },
    "紫苑灵草": {
        "name": "紫苑灵草",
        "desc": "可润肺化痰，是疗伤丹与养元丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 10,
    },
    "款冬灵花": {
        "name": "款冬灵花",
        "desc": "可润肺下气，是养元丹的辅药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 12,
    },
    "白前灵根": {
        "name": "白前灵根",
        "desc": "可降气化痰，是疗伤丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 11,
    },
    "前胡灵根": {
        "name": "前胡灵根",
        "desc": "可疏散风热，是解毒丹与清心丹的辅材。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 9,
    },
    "桔梗灵根": {
        "name": "桔梗灵根",
        "desc": "可宣肺利咽，是疗伤丹与养元丹的辅药。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 14,
    },
    "川贝灵母": {
        "name": "川贝灵母",
        "desc": "可清热化痰，是养元丹与清心丹的辅料。",
        "type": "herb",
        "rarity": "普通",
        "element": None,
        "sell_price": 15,
    },
    "冰晶草": {
        "name": "冰晶草",
        "desc": "雪山灵草，叶缘凝冰，可炼冰属丹药与清心丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "水",
        "sell_price": 87,
    },
    "赤心莲": {
        "name": "赤心莲",
        "desc": "地火泉旁所生灵莲，莲心灼热，可炼火属丹药与淬体丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "火",
        "sell_price": 91,
    },
    "雷芽草": {
        "name": "雷芽草",
        "desc": "雷雨过后才发的灵草嫩芽，可炼雷属丹药与破障丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "雷",
        "sell_price": 89,
    },
    "青灵藤": {
        "name": "青灵藤",
        "desc": "灵气充沛处所生灵藤，生机盎然，可炼木属丹药与疗伤丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "木",
        "sell_price": 86,
    },
    "地灵根": {
        "name": "地灵根",
        "desc": "地脉灵穴所生灵根，厚重沉稳，可炼土属丹药与固本丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "土",
        "sell_price": 85,
    },
    "霜叶莲": {
        "name": "霜叶莲",
        "desc": "寒地灵莲，叶带霜纹，可炼冰属丹药与延寿丹辅药。",
        "type": "herb",
        "rarity": "稀有",
        "element": "水",
        "sell_price": 90,
    },
    "焰尾花": {
        "name": "焰尾花",
        "desc": "花瓣如焰的灵花，可炼火属丹药与纯阳丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "火",
        "sell_price": 93,
    },
    "雷藤心": {
        "name": "雷藤心",
        "desc": "雷击灵藤所取藤心，可炼雷属丹药与破境丹辅药。",
        "type": "herb",
        "rarity": "稀有",
        "element": "雷",
        "sell_price": 92,
    },
    "碧木果": {
        "name": "碧木果",
        "desc": "灵木所结碧果，木灵充沛，可炼木属丹药与养元丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "木",
        "sell_price": 88,
    },
    "山黄精灵块": {
        "name": "山黄精灵块",
        "desc": "灵山黄精结块，土灵内蕴，可炼土属丹药与培元丹。",
        "type": "herb",
        "rarity": "稀有",
        "element": "土",
        "sell_price": 87,
    },
    "碧落灵参": {
        "name": "碧落灵参",
        "desc": "传说碧落天界坠落的灵参，可大补元气，是续命丹与飞升丹的珍贵辅药。",
        "type": "herb",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 350,
    },
    "黄泉彼岸花": {
        "name": "黄泉彼岸花",
        "desc": "黄泉河畔所生灵花，可炼还魂丹与轮回类丹药。",
        "type": "herb",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 370,
    },
    "星辰悟道果": {
        "name": "星辰悟道果",
        "desc": "吸收星力所结灵果，可助悟道破障，是悟道丹的核心辅药。",
        "type": "herb",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 390,
    },
    "瑶池金莲": {
        "name": "瑶池金莲",
        "desc": "传说瑶池所生灵莲，可炼仙丹与飞升丹，极为难得。",
        "type": "herb",
        "rarity": "绝世",
        "element": None,
        "sell_price": 4800,
    },
}
