MATERIALS = {
    "铜矿石": {
        "name": "铜矿石",
        "desc": "最常见的矿石，可冶炼为铜锭，用于基础炼器。",
        "type": "ore",
        "rarity": "普通",
        "element": None,
        "sell_price": 5,
    },
    "铁矿石": {
        "name": "铁矿石",
        "desc": "坚硬的铁矿，冶炼后可锻造凡铁兵器。",
        "type": "ore",
        "rarity": "普通",
        "element": None,
        "sell_price": 8,
    },
    "银矿石": {
        "name": "银矿石",
        "desc": "银白色矿石，含微量灵气，可用于炼制低阶法器。",
        "type": "ore",
        "rarity": "普通",
        "element": None,
        "sell_price": 15,
    },
    "精铁矿": {
        "name": "精铁矿",
        "desc": "品质上乘的铁矿，杂质极少，是锻造良器的基础材料。",
        "type": "ore",
        "rarity": "普通",
        "element": None,
        "sell_price": 20,
    },
    "灵铁矿": {
        "name": "灵铁矿",
        "desc": "蕴含灵气的铁矿，可锻造灵器级别的装备。",
        "type": "ore",
        "rarity": "普通",
        "element": None,
        "sell_price": 35,
    },
    "秘银矿": {
        "name": "秘银矿",
        "desc": "稀有的秘银矿脉产出，质地轻盈坚韧，是中阶炼器的上选。",
        "type": "ore",
        "rarity": "稀有",
        "element": None,
        "sell_price": 60,
    },
    "玄铁矿": {
        "name": "玄铁矿",
        "desc": "深黑色的玄铁，硬度极高，锻造后刀枪不入。",
        "type": "ore",
        "rarity": "稀有",
        "element": None,
        "sell_price": 80,
    },
    "陨铁矿": {
        "name": "陨铁矿",
        "desc": "天外陨石中提取的矿石，自带星辰之力。",
        "type": "ore",
        "rarity": "稀有",
        "element": None,
        "sell_price": 120,
    },
    "寒冰铁": {
        "name": "寒冰铁",
        "desc": "万年寒窟中形成的冰属矿石，触之刺骨，水属灵根修士的炼器至宝。",
        "type": "ore",
        "rarity": "稀有",
        "element": "水",
        "sell_price": 100,
    },
    "赤炎石": {
        "name": "赤炎石",
        "desc": "地火淬炼而成的火属矿石，表面常年灼热，可大幅提升火属法器威力。",
        "type": "ore",
        "rarity": "稀有",
        "element": "火",
        "sell_price": 100,
    },
    "雷灵矿": {
        "name": "雷灵矿",
        "desc": "雷劫落地后凝结的矿石，内含雷霆之力，极为罕见。",
        "type": "ore",
        "rarity": "稀有",
        "element": "雷",
        "sell_price": 110,
    },
    "青木精": {
        "name": "青木精",
        "desc": "万年灵木根系深处结出的木属矿晶，蕴含蓬勃生机。",
        "type": "ore",
        "rarity": "稀有",
        "element": "木",
        "sell_price": 100,
    },
    "厚土精": {
        "name": "厚土精",
        "desc": "大地深处凝聚的土属精华，沉稳厚重，可强化防具根基。",
        "type": "ore",
        "rarity": "稀有",
        "element": "土",
        "sell_price": 100,
    },
    "紫金矿": {
        "name": "紫金矿",
        "desc": "泛着紫金光泽的珍稀矿石，是锻造高阶法器的核心材料。",
        "type": "ore",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 200,
    },
    "九天玄铁": {
        "name": "九天玄铁",
        "desc": "九天之上坠落的神铁，坚逾万物，传说可铸神兵。",
        "type": "ore",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 300,
    },
    "太阴寒铁": {
        "name": "太阴寒铁",
        "desc": "太阴之精凝结的极品冰铁，寒气可冻结神识。",
        "type": "ore",
        "rarity": "珍贵",
        "element": "水",
        "sell_price": 280,
    },
    "太阳真金": {
        "name": "太阳真金",
        "desc": "太阳精火淬炼亿万年的极品火金，熔点极高，锻造时需天火相助。",
        "type": "ore",
        "rarity": "珍贵",
        "element": "火",
        "sell_price": 280,
    },
    "五行母矿": {
        "name": "五行母矿",
        "desc": "同时蕴含金木水火土五行之力的神矿，万中无一。",
        "type": "ore",
        "rarity": "绝世",
        "element": "五行",
        "sell_price": 2000,
    },
    "混沌神铁": {
        "name": "混沌神铁",
        "desc": "混沌未开时遗留的太古神铁，蕴含开天辟地之力。",
        "type": "ore",
        "rarity": "绝世",
        "element": None,
        "sell_price": 3500,
    },
    "鸿蒙陨铁": {
        "name": "鸿蒙陨铁",
        "desc": "鸿蒙初判时的天外之物，传说以此铸器可斩仙弑神。",
        "type": "ore",
        "rarity": "绝世",
        "element": None,
        "sell_price": 5000,
    },
    "锡矿石": {
        "name": "锡矿石",
        "desc": "质地柔软的锡矿，常与铜合炼，可铸低阶法器的辅材。",
        "type": "ore",
        "rarity": "普通",
        "element": None,
        "sell_price": 4,
    },
    "铅矿石": {
        "name": "铅矿石",
        "desc": "沉甸甸的铅矿，可镇邪辟煞，亦可用于炼制某些阴属丹方。",
        "type": "ore",
        "rarity": "普通",
        "element": None,
        "sell_price": 6,
    },
    "青金石": {
        "name": "青金石",
        "desc": "色泽湛蓝的宝石矿，研磨成粉可绘符箓、布阵纹，低阶修士常用。",
        "type": "ore",
        "rarity": "普通",
        "element": None,
        "sell_price": 12,
    },
    "云母矿": {
        "name": "云母矿",
        "desc": "层层剥离如云片的矿石，可隔绝灵力波动，是布置隐匿阵法的好材料。",
        "type": "ore",
        "rarity": "普通",
        "element": None,
        "sell_price": 18,
    },
    "碧玺矿": {
        "name": "碧玺矿",
        "desc": "内蕴微光的碧色矿石，能缓慢吸纳天地灵气，可作聚灵阵的阵眼辅材。",
        "type": "ore",
        "rarity": "普通",
        "element": None,
        "sell_price": 25,
    },
    "血玉矿": {
        "name": "血玉矿",
        "desc": "殷红如血的玉矿，传说为古战场血气浸染所化，可炼血道法器。",
        "type": "ore",
        "rarity": "稀有",
        "element": None,
        "sell_price": 70,
    },
    "墨玉矿": {
        "name": "墨玉矿",
        "desc": "漆黑如墨的玉石，生于极阴之地，阴属修士炼器的上佳之选。",
        "type": "ore",
        "rarity": "稀有",
        "element": None,
        "sell_price": 75,
    },
    "风纹石": {
        "name": "风纹石",
        "desc": "表面天然生有风纹的奇石，轻若无物，可炼飞行法器或风属法宝。",
        "type": "ore",
        "rarity": "稀有",
        "element": "风",
        "sell_price": 85,
    },
    "地心炎晶": {
        "name": "地心炎晶",
        "desc": "地脉岩浆深处凝结的火晶，炽烈无比，是炼制火属灵器的珍稀材料。",
        "type": "ore",
        "rarity": "稀有",
        "element": "火",
        "sell_price": 95,
    },
    "霜华玉": {
        "name": "霜华玉",
        "desc": "冰雪秘境中诞生的玉髓，触之生寒，可炼冰属性法剑与护甲。",
        "type": "ore",
        "rarity": "稀有",
        "element": "水",
        "sell_price": 95,
    },
    "金刚砂": {
        "name": "金刚砂",
        "desc": "佛门圣地或金刚矿脉所出，坚不可摧，可淬炼佛门法器与护身法宝。",
        "type": "ore",
        "rarity": "稀有",
        "element": None,
        "sell_price": 90,
    },
    "碧落石": {
        "name": "碧落石",
        "desc": "传说自碧落天界坠落的灵石，内蕴一丝仙灵之气，珍贵异常。",
        "type": "ore",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 220,
    },
    "黄泉铁": {
        "name": "黄泉铁",
        "desc": "幽冥黄泉河畔所产的阴铁，可铸勾魂索、幽冥幡等鬼道至宝。",
        "type": "ore",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 240,
    },
    "星辰钢": {
        "name": "星辰钢",
        "desc": "以陨星之核反复锻打而成，蕴含星辰之力，可铸本命飞剑的剑胚。",
        "type": "ore",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 260,
    },
    "龙鳞矿": {
        "name": "龙鳞矿",
        "desc": "上古真龙蜕鳞之地衍生的矿脉，鳞纹隐约可见，炼器可得龙威加持。",
        "type": "ore",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 320,
    },
    "凤血石": {
        "name": "凤血石",
        "desc": "凤凰涅槃时精血滴落所化的赤石，蕴含涅槃真意，可炼重生类法宝。",
        "type": "ore",
        "rarity": "珍贵",
        "element": "火",
        "sell_price": 350,
    },
    "麒麟玉": {
        "name": "麒麟玉",
        "desc": "祥瑞麒麟踏足之地凝结的灵玉，可辟邪纳福，炼成护身玉牌可挡灾劫。",
        "type": "ore",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 340,
    },
    "虚空晶": {
        "name": "虚空晶",
        "desc": "空间裂隙中偶然凝结的晶石，可炼制储物戒、传送阵等空间类至宝。",
        "type": "ore",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 380,
    },
    "造化神石": {
        "name": "造化神石",
        "desc": "传闻为造化玉碟碎片所化，内蕴一丝造化之力，可点化灵器、孕育器灵。",
        "type": "ore",
        "rarity": "绝世",
        "element": None,
        "sell_price": 2500,
    },
    "补天石": {
        "name": "补天石",
        "desc": "女娲补天所遗的五色神石碎片，蕴含补天功德，乃炼化本命道器的无上神材。",
        "type": "ore",
        "rarity": "绝世",
        "element": None,
        "sell_price": 4000,
    },
}
