PILLS = {
    "筑基丹": {
        "name": "筑基丹",
        "desc": "炼气期修士突破筑基的必备丹药，服用后大幅提升突破成功率。",
        "type": "pill",
        "rarity": "稀有",
        "effect": {"breakthrough_bonus": 40},
    },
    "凝丹丹": {
        "name": "凝丹丹",
        "desc": "筑基期圆满修士凝结金丹所用，服用后大幅提升结丹成功率。",
        "type": "pill",
        "rarity": "珍贵",
        "effect": {"breakthrough_bonus": 35},
    },
    "化婴丹": {
        "name": "化婴丹",
        "desc": "结丹期后期修士化婴所用，服用后提升元婴突破成功率。",
        "type": "pill",
        "rarity": "绝世",
        "effect": {"breakthrough_bonus": 30},
    },
    "聚灵丹": {
        "name": "聚灵丹",
        "desc": "服用后修炼速度提升50%，持续效果在下次修炼时生效。",
        "type": "pill",
        "rarity": "普通",
        "effect": {"cultivation_speed_bonus": 50},
    },
    "续命丹": {
        "name": "续命丹",
        "desc": "珍贵丹药，服用后恢复30年寿元，不可超过寿元上限。",
        "type": "pill",
        "rarity": "稀有",
        "effect": {"lifespan": 30},
    },
    "破障丹": {
        "name": "破障丹",
        "desc": "突破瓶颈时服用，提升所有境界突破成功率20%。",
        "type": "pill",
        "rarity": "稀有",
        "effect": {"breakthrough_bonus": 20},
    },
    "小延寿丹": {
        "name": "小延寿丹",
        "desc": "以灵草炼制的延寿丹药，服用后寿元 +5年，可突破上限。",
        "type": "pill",
        "rarity": "普通",
        "effect": {"lifespan_extend": 5},
    },
    "延寿丹": {
        "name": "延寿丹",
        "desc": "正统延寿丹方，服用后寿元 +10年，可突破上限。",
        "type": "pill",
        "rarity": "普通",
        "effect": {"lifespan_extend": 10},
    },
    "大延寿丹": {
        "name": "大延寿丹",
        "desc": "上品延寿丹药，服用后寿元 +15年，可突破上限。",
        "type": "pill",
        "rarity": "稀有",
        "effect": {"lifespan_extend": 15},
    },
    "九转延寿丹": {
        "name": "九转延寿丹",
        "desc": "九转炼制的珍贵丹药，服用后寿元 +20年，可突破上限。",
        "type": "pill",
        "rarity": "稀有",
        "effect": {"lifespan_extend": 20},
    },
    "不死丹": {
        "name": "不死丹",
        "desc": "传说中的仙丹，服用后寿元 +30年，可突破上限。",
        "type": "pill",
        "rarity": "珍贵",
        "effect": {"lifespan_extend": 30},
    },
    "万寿丹": {
        "name": "万寿丹",
        "desc": "万年难遇的至宝，服用后寿元 +50年，可突破上限。",
        "type": "pill",
        "rarity": "绝世",
        "effect": {"lifespan_extend": 50},
    },
}
