WOOD = {
    "白杨木": {
        "name": "白杨木",
        "desc": "最常见的灵木，质地松软，可制作低阶符纸与阵旗。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 5,
    },
    "松灵木": {
        "name": "松灵木",
        "desc": "百年灵松所产，木质坚韧，是炼制木属法器的基础材料。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 8,
    },
    "铁桦木": {
        "name": "铁桦木",
        "desc": "硬度堪比精铁的灵木，常用于锻造法器的柄部与弓身。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 15,
    },
    "紫檀灵木": {
        "name": "紫檀灵木",
        "desc": "散发淡淡檀香的灵木，可安神定魄，是炼制辅助类法器的良材。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 20,
    },
    "青冥竹": {
        "name": "青冥竹",
        "desc": "生于灵气充沛之地的翠竹，中空蕴灵，可制竹简、竹笛等法器。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 12,
    },
    "雷击木": {
        "name": "雷击木",
        "desc": "被天雷劈中后存活的灵木，木中残留雷霆之力，可炼雷属法器。",
        "type": "wood",
        "rarity": "稀有",
        "element": "雷",
        "sell_price": 90,
    },
    "寒霜柏": {
        "name": "寒霜柏",
        "desc": "万年冰原上生长的古柏，木质冰寒入骨，水属灵根修士的炼器佳材。",
        "type": "wood",
        "rarity": "稀有",
        "element": "水",
        "sell_price": 95,
    },
    "火凤梧桐": {
        "name": "火凤梧桐",
        "desc": "传说凤凰栖息的梧桐木，木中蕴含火灵之气，燃之不尽。",
        "type": "wood",
        "rarity": "稀有",
        "element": "火",
        "sell_price": 100,
    },
    "建木枝": {
        "name": "建木枝",
        "desc": "上古神木建木的断枝，蕴含沟通天地的神异之力，可炼空间类法宝。",
        "type": "wood",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 380,
    },
    "扶桑神木": {
        "name": "扶桑神木",
        "desc": "太阳栖息之树的碎片，内蕴纯阳真火，乃炼制至阳法宝的无上神材。",
        "type": "wood",
        "rarity": "绝世",
        "element": "火",
        "sell_price": 4500,
    },
    "柳灵木": {
        "name": "柳灵木",
        "desc": "河边灵柳所产，木质柔韧，可编符箓载体与简易阵旗。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 5,
    },
    "樟灵木": {
        "name": "樟灵木",
        "desc": "百年灵樟之材，自带驱邪之香，可制香炉、辟邪符牌。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 7,
    },
    "枫灵木": {
        "name": "枫灵木",
        "desc": "秋日灵枫所伐，木纹如焰，可作低阶法器的柄材。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 9,
    },
    "榆灵木": {
        "name": "榆灵木",
        "desc": "山间灵榆质地坚硬，常用来炼制护身木牌与阵基。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 8,
    },
    "槐灵木": {
        "name": "槐灵木",
        "desc": "古槐通灵之材，阴气适中，可制招魂幡、阴属符纸。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 10,
    },
    "桃灵木": {
        "name": "桃灵木",
        "desc": "灵桃木辟邪克鬼，是炼制桃木剑、驱邪法器的首选。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 12,
    },
    "杏灵木": {
        "name": "杏灵木",
        "desc": "灵杏木质细腻，可雕符印、制琴身，低阶修士常用。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 8,
    },
    "桂灵木": {
        "name": "桂灵木",
        "desc": "月宫桂树旁支所产，木质清香，可炼安神香与辅助法器。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 14,
    },
    "桑灵木": {
        "name": "桑灵木",
        "desc": "灵蚕所食之桑，木质柔韧含灵，可织符布、制弦。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 11,
    },
    "梧桐灵木": {
        "name": "梧桐灵木",
        "desc": "寻常梧桐得灵气滋养所成，可制琴、制匣，收纳灵物。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 10,
    },
    "乌木": {
        "name": "乌木",
        "desc": "沉于水底多年的灵木，色黑质密，可炼阴属法器与棺椁。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 16,
    },
    "黄杨灵木": {
        "name": "黄杨灵木",
        "desc": "生长极慢的灵黄杨，木质细密，可雕阵盘、符印。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 13,
    },
    "沉香木": {
        "name": "沉香木",
        "desc": "灵沉香结香之材，燃之可定心凝神，是炼香道法器的好料。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 18,
    },
    "花梨灵木": {
        "name": "花梨灵木",
        "desc": "灵花梨木纹华美，质地坚实，可炼法杖、拂尘柄。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 15,
    },
    "楠灵木": {
        "name": "楠灵木",
        "desc": "灵楠耐腐防虫，可制储物匣、经书架，久存不坏。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 14,
    },
    "桧灵木": {
        "name": "桧灵木",
        "desc": "高山灵桧所产，含淡淡松香，可炼静心类法器。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 9,
    },
    "椴灵木": {
        "name": "椴灵木",
        "desc": "灵椴木质轻软，易刻符纹，是制作符纸原坯的常用材。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 6,
    },
    "楸灵木": {
        "name": "楸灵木",
        "desc": "灵楸木纹直顺，可制箭杆、枪杆等长兵器的木芯。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 10,
    },
    "柘灵木": {
        "name": "柘灵木",
        "desc": "灵柘木质硬而韧，古时多用于制弓，可炼灵弓弓身。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 17,
    },
    "菩提枝": {
        "name": "菩提枝",
        "desc": "灵山菩提树的落枝，带一丝禅意，可制念珠、禅杖。",
        "type": "wood",
        "rarity": "普通",
        "element": None,
        "sell_price": 20,
    },
    "雷纹木": {
        "name": "雷纹木",
        "desc": "遭雷击而不死的灵木，木心留有雷纹，可炼雷属符箓与法器。",
        "type": "wood",
        "rarity": "稀有",
        "element": "雷",
        "sell_price": 92,
    },
    "冰心竹": {
        "name": "冰心竹",
        "desc": "雪山灵竹，竹心蕴寒，可制冰属法笛、寒属性阵旗。",
        "type": "wood",
        "rarity": "稀有",
        "element": "水",
        "sell_price": 93,
    },
    "赤焰松": {
        "name": "赤焰松",
        "desc": "地火脉旁生长的灵松，木质含火灵，可炼火属法杖。",
        "type": "wood",
        "rarity": "稀有",
        "element": "火",
        "sell_price": 98,
    },
    "碧血灵藤": {
        "name": "碧血灵藤",
        "desc": "古战场遗址所生的灵藤，藤心泛红，可炼血道与木属法器。",
        "type": "wood",
        "rarity": "稀有",
        "element": "木",
        "sell_price": 90,
    },
    "玄黄土根": {
        "name": "玄黄土根",
        "desc": "地脉深处灵树之根，厚重载物，可炼土属阵基与防具。",
        "type": "wood",
        "rarity": "稀有",
        "element": "土",
        "sell_price": 91,
    },
    "风吟木": {
        "name": "风吟木",
        "desc": "高崖风口所长之木，遇风自鸣，可炼飞行法器与风属法宝。",
        "type": "wood",
        "rarity": "稀有",
        "element": None,
        "sell_price": 95,
    },
    "月华桂": {
        "name": "月华桂",
        "desc": "吸收月华成灵的桂木，可炼阴属、太阴类法器。",
        "type": "wood",
        "rarity": "稀有",
        "element": None,
        "sell_price": 94,
    },
    "龙血木": {
        "name": "龙血木",
        "desc": "传说沾过真龙之血的灵木，木质赤红，可炼龙威法器。",
        "type": "wood",
        "rarity": "稀有",
        "element": None,
        "sell_price": 99,
    },
    "凤栖枝": {
        "name": "凤栖枝",
        "desc": "凤凰曾栖之枝，木中残留一丝涅槃火意。",
        "type": "wood",
        "rarity": "稀有",
        "element": "火",
        "sell_price": 100,
    },
    "鬼哭藤": {
        "name": "鬼哭藤",
        "desc": "幽冥地界边缘所生之藤，阴气极重，可炼鬼道法器。",
        "type": "wood",
        "rarity": "稀有",
        "element": None,
        "sell_price": 88,
    },
    "星辰木": {
        "name": "星辰木",
        "desc": "吸收星力成长的灵木，木质泛银光，可炼星属法宝。",
        "type": "wood",
        "rarity": "稀有",
        "element": None,
        "sell_price": 96,
    },
    "千年灵檀": {
        "name": "千年灵檀",
        "desc": "千年灵檀心材，香气可助悟道，可炼高阶辅助法宝与香道至宝。",
        "type": "wood",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 260,
    },
    "若木枝": {
        "name": "若木枝",
        "desc": "上古若木的残枝，传说为日入之处神树，可炼至阳法器。",
        "type": "wood",
        "rarity": "珍贵",
        "element": "火",
        "sell_price": 320,
    },
    "寻木心": {
        "name": "寻木心",
        "desc": "寻木之芯，传说此木上达天听，可炼沟通天地的法阵核心。",
        "type": "wood",
        "rarity": "珍贵",
        "element": None,
        "sell_price": 350,
    },
    "不死树皮": {
        "name": "不死树皮",
        "desc": "不死神树蜕下的树皮，内蕴生机，可炼续命、重生类法宝。",
        "type": "wood",
        "rarity": "珍贵",
        "element": "木",
        "sell_price": 400,
    },
    "苦海菩提": {
        "name": "苦海菩提",
        "desc": "苦海边菩提古树所结之材，可炼渡劫、护心类绝世法器。",
        "type": "wood",
        "rarity": "绝世",
        "element": None,
        "sell_price": 2500,
    },
    "月桂神枝": {
        "name": "月桂神枝",
        "desc": "广寒宫月桂神树之枝，太阴之精凝结，乃炼太阴至宝的无上神材。",
        "type": "wood",
        "rarity": "绝世",
        "element": "水",
        "sell_price": 3200,
    },
    "世界树残枝": {
        "name": "世界树残枝",
        "desc": "上古世界树崩毁后的残枝，蕴含一方世界雏形之力。",
        "type": "wood",
        "rarity": "绝世",
        "element": None,
        "sell_price": 4000,
    },
    "混沌灵根": {
        "name": "混沌灵根",
        "desc": "混沌中诞生的灵木之根，可炼化混沌、开天类无上道器。",
        "type": "wood",
        "rarity": "绝世",
        "element": None,
        "sell_price": 5000,
    },
}
