COMMON_QUESTS = [
    {
        "id": "c007",
        "title": "驱逐恶灵",
        "desc": "城郊古庙近日闹鬼，居民惶惶不安，需修士前往驱逐低阶恶灵。",
        "type": "combat",
        "req": {"min_realm": "炼气期1层"},
        "enemy": {"name": "低阶恶灵", "power": 25},
        "rewards": {"spirit_stones": 700, "reputation": 8, "cultivation": 40},
    },
    {
        "id": "c008",
        "title": "寻找失踪商人",
        "desc": "一名商人前往百草谷采购后失踪，家属悬赏寻人。",
        "type": "gather",
        "req": {"min_realm": "炼气期1层"},
        "location": "百草谷",
        "rewards": {"spirit_stones": 500, "reputation": 10, "fortune": 1},
    },
    {
        "id": "c009",
        "title": "清剿盗墓贼",
        "desc": "古战场附近出现盗墓贼，亵渎先人遗骸，需驱逐。",
        "type": "combat",
        "req": {"min_realm": "炼气期2层"},
        "enemy": {"name": "盗墓贼头目", "power": 45},
        "rewards": {"spirit_stones": 900, "reputation": 12, "cultivation": 60},
    },
    {
        "id": "c010",
        "title": "采集寒铁矿",
        "desc": "铁匠铺急需一批寒铁矿石，需前往漠北荒漠开采。",
        "type": "gather",
        "req": {"min_realm": "炼气期2层"},
        "location": "漠北荒漠",
        "rewards": {"spirit_stones": 800, "reputation": 8, "physique": 1},
    },
    {
        "id": "c011",
        "title": "击退野狼群",
        "desc": "城外农庄遭野狼群袭扰，庄主出资悬赏驱逐。",
        "type": "combat",
        "req": {"min_realm": "炼气期1层"},
        "enemy": {"name": "狼王", "power": 35},
        "rewards": {"spirit_stones": 750, "reputation": 9, "cultivation": 45},
    },
    {
        "id": "c012",
        "title": "捕捉灵蝶",
        "desc": "炼丹师需要万妖岭边缘的七彩灵蝶作为药引，出价不菲。",
        "type": "gather",
        "req": {"min_realm": "炼气期3层"},
        "location": "万妖岭",
        "rewards": {"spirit_stones": 1000, "reputation": 10, "soul": 1},
    },
    {
        "id": "c013",
        "title": "护送丹药",
        "desc": "灵药宗委托将一批丹药安全送达，途中需防范劫匪。",
        "type": "combat",
        "req": {"min_realm": "炼气期4层"},
        "enemy": {"name": "截道劫匪", "power": 75},
        "rewards": {"spirit_stones": 1600, "reputation": 18, "cultivation": 90},
    },
    {
        "id": "c014",
        "title": "采集幽冥草",
        "desc": "幽冥镇附近的幽冥草是炼制辟邪丹的关键材料。",
        "type": "gather",
        "req": {"min_realm": "炼气期4层"},
        "location": "幽冥镇",
        "rewards": {"spirit_stones": 1100, "reputation": 12, "bone": 1},
    },
    {
        "id": "c015",
        "title": "剿灭邪修散修",
        "desc": "一名邪修散修在城郊作乱，伤及无辜，需尽快处置。",
        "type": "combat",
        "req": {"min_realm": "炼气期5层"},
        "enemy": {"name": "邪修散修", "power": 100},
        "rewards": {"spirit_stones": 2200, "reputation": 22, "cultivation": 110},
    },
    {
        "id": "c016",
        "title": "探查异动",
        "desc": "古战场近日灵气异动，需修士前往探查原因并带回报告。",
        "type": "gather",
        "req": {"min_realm": "炼气期6层"},
        "location": "古战场",
        "rewards": {"spirit_stones": 1400, "reputation": 15, "comprehension": 1},
    },
    {
        "id": "c001",
        "title": "驱逐采花贼",
        "desc": "城郊近日出没一名采花贼，已有数名女修受害，茶馆悬赏捉拿。",
        "type": "combat",
        "req": {"min_realm": "炼气期1层"},
        "enemy": {"name": "采花贼", "power": 30},
        "rewards": {"spirit_stones": 800, "reputation": 10, "cultivation": 50},
    },
    {
        "id": "c002",
        "title": "剿灭山贼",
        "desc": "官道上的山贼劫掠商旅，商会出资悬赏，击退即可领赏。",
        "type": "combat",
        "req": {"min_realm": "炼气期3层"},
        "enemy": {"name": "山贼头目", "power": 60},
        "rewards": {"spirit_stones": 1500, "reputation": 15, "cultivation": 80},
    },
    {
        "id": "c003",
        "title": "采集灵草",
        "desc": "药铺急需百草谷的青心草，需前往百草谷采集10株。",
        "type": "gather",
        "req": {"min_realm": "炼气期1层"},
        "location": "百草谷",
        "rewards": {"spirit_stones": 600, "reputation": 8, "soul": 1},
    },
    {
        "id": "c004",
        "title": "挖取灵石矿",
        "desc": "漠北荒漠发现新矿脉，需前往开采一批地阶灵石。",
        "type": "gather",
        "req": {"min_realm": "炼气期3层"},
        "location": "漠北荒漠",
        "rewards": {"spirit_stones": 1200, "reputation": 10, "physique": 1},
    },
    {
        "id": "c005",
        "title": "护送商队",
        "desc": "一支商队需要护送至下一城市，途中可能遭遇劫匪。",
        "type": "combat",
        "req": {"min_realm": "炼气期5层"},
        "enemy": {"name": "劫匪", "power": 90},
        "rewards": {"spirit_stones": 2000, "reputation": 20, "cultivation": 100},
    },
    {
        "id": "c006",
        "title": "捕捉妖兽",
        "desc": "万妖岭边缘出现低阶妖兽扰民，需前往驱逐。",
        "type": "gather",
        "req": {"min_realm": "炼气期5层"},
        "location": "万妖岭",
        "rewards": {"spirit_stones": 1800, "reputation": 15, "bone": 1},
    },
]
