ELITE_QUESTS = [
    {
        "id": "e006",
        "title": "追杀逃亡邪修",
        "desc": "一名从宗门叛逃的邪修携带机密功法出逃，各大宗门联合悬赏追杀。",
        "type": "combat",
        "req": {"min_realm": "筑基期1层"},
        "enemy": {"name": "叛逃邪修", "power": 280},
        "rewards": {"spirit_stones": 4500, "reputation": 38, "cultivation": 280,
                    "technique": "缩地术"},
    },
    {
        "id": "e007",
        "title": "昆仑秘境外围探查",
        "desc": "昆仑秘境外围出现异常灵气波动，需有经验的修士前往探查。",
        "type": "gather",
        "req": {"min_realm": "筑基期2层", "min_stat": {"soul": 6}},
        "location": "昆仑秘境",
        "rewards": {"spirit_stones": 3500, "reputation": 30, "soul": 1,
                    "technique": "望气术"},
    },
    {
        "id": "e008",
        "title": "天雷谷采集雷晶",
        "desc": "天雷谷中的雷晶是炼制雷属法器的珍贵材料，价值极高。",
        "type": "gather",
        "req": {"min_realm": "筑基期3层", "min_stat": {"bone": 6}},
        "location": "天雷谷",
        "rewards": {"spirit_stones": 5500, "reputation": 42, "bone": 1,
                    "technique": "固元功"},
    },
    {
        "id": "e009",
        "title": "击败擂台霸主",
        "desc": "铁甲城擂台出现一名横扫众人的霸主，血煞门出资悬赏能击败此人者。",
        "type": "combat",
        "req": {"min_realm": "筑基期4层", "min_stat": {"physique": 8}},
        "enemy": {"name": "擂台霸主", "power": 450},
        "rewards": {"spirit_stones": 6500, "reputation": 48, "physique": 1,
                    "technique": "破军刀法"},
    },
    {
        "id": "e010",
        "title": "虚空裂缝外围采集",
        "desc": "虚空裂缝边缘漂浮着大量虚空晶石，是极为珍贵的炼器材料。",
        "type": "gather",
        "req": {"min_realm": "筑基期6层"},
        "location": "虚空裂缝",
        "rewards": {"spirit_stones": 7500, "reputation": 52, "lifespan": 8,
                    "technique": "千机变"},
    },
    {
        "id": "e011",
        "title": "斩杀血煞魔头",
        "desc": "一名修炼邪功的魔头在幽冥海附近大肆杀戮，鬼修宗悬赏极高。",
        "type": "combat",
        "req": {"min_realm": "筑基期2层", "min_stat": {"soul": 7}},
        "enemy": {"name": "血煞魔头", "power": 320},
        "rewards": {"spirit_stones": 5200, "reputation": 44, "soul": 1,
                    "technique": "玄天心法"},
    },
    {
        "id": "e012",
        "title": "万妖岭深处采药",
        "desc": "万妖岭深处生长着千年灵芝，药效极强，但妖兽密集危险极高。",
        "type": "gather",
        "req": {"min_realm": "筑基期5层", "min_stat": {"fortune": 6}},
        "location": "万妖岭",
        "rewards": {"spirit_stones": 6800, "reputation": 50, "lifespan": 12,
                    "technique": "吞星功"},
    },
    {
        "id": "e013",
        "title": "剿灭妖兽巢穴",
        "desc": "寒玉窟附近出现大型妖兽巢穴，威胁周边城市安全，需彻底清剿。",
        "type": "combat",
        "req": {"min_realm": "筑基期7层", "min_stat": {"physique": 8}},
        "enemy": {"name": "妖兽巢主", "power": 600},
        "rewards": {"spirit_stones": 9000, "reputation": 60, "physique": 1,
                    "technique": "罡气护体"},
    },
    {
        "id": "e014",
        "title": "古战场遗迹探索",
        "desc": "古战场深处发现一处上古遗迹，内有大量修炼资源，需强者前往探索。",
        "type": "gather",
        "req": {"min_realm": "筑基期8层", "min_stat": {"comprehension": 8}},
        "location": "古战场",
        "rewards": {"spirit_stones": 8500, "reputation": 58, "comprehension": 1,
                    "technique": "穿云剑法"},
    },
    {
        "id": "e015",
        "title": "击败幽冥海守卫",
        "desc": "幽冥海深处有一名强力守卫阻拦所有进入者，噬魂阁悬赏击败此人。",
        "type": "combat",
        "req": {"min_realm": "筑基期9层", "min_stat": {"soul": 8}},
        "enemy": {"name": "幽冥守卫", "power": 700},
        "rewards": {"spirit_stones": 10000, "reputation": 65, "soul": 1,
                    "technique": "万象归一"},
    },
    {
        "id": "e001",
        "title": "斩杀江洋大盗",
        "desc": "江湖上臭名昭著的「血手魔」流窜至此，官府悬赏极高，但此人修为不低。",
        "type": "combat",
        "req": {"min_realm": "筑基期1层"},
        "enemy": {"name": "血手魔", "power": 300},
        "rewards": {"spirit_stones": 5000, "reputation": 40, "cultivation": 300,
                    "technique": "金钟罩"},
    },
    {
        "id": "e002",
        "title": "深入古战场",
        "desc": "古战场深处发现一处封印，需要修士前往探查并带回残留的功法碎简。",
        "type": "gather",
        "req": {"min_realm": "筑基期3层", "min_stat": {"comprehension": 7}},
        "location": "古战场",
        "rewards": {"spirit_stones": 4000, "reputation": 35, "comprehension": 1,
                    "technique": "穿云剑法"},
    },
    {
        "id": "e003",
        "title": "寒玉窟探险",
        "desc": "寒玉窟深处有一批万年寒玉，但守护的冰系妖兽极为凶猛。",
        "type": "gather",
        "req": {"min_realm": "筑基期5层", "min_stat": {"physique": 7}},
        "location": "寒玉窟",
        "rewards": {"spirit_stones": 6000, "reputation": 45, "physique": 1,
                    "technique": "罡气护体"},
    },
    {
        "id": "e004",
        "title": "剿灭邪修据点",
        "desc": "一伙邪修在城郊建立据点，为祸一方，宗门联合悬赏清剿。",
        "type": "combat",
        "req": {"min_realm": "筑基期5层", "min_stat": {"soul": 7}},
        "enemy": {"name": "邪修首领", "power": 500},
        "rewards": {"spirit_stones": 7000, "reputation": 50, "soul": 1,
                    "technique": "万象归一"},
    },
    {
        "id": "e005",
        "title": "幽冥海采珠",
        "desc": "幽冥海深处的灵珠是炼制高阶丹药的关键材料，价值连城。",
        "type": "gather",
        "req": {"min_realm": "筑基期7层"},
        "location": "幽冥海",
        "rewards": {"spirit_stones": 8000, "reputation": 55, "lifespan": 10,
                    "technique": "神行百变"},
    },
]
