LEGENDARY_QUESTS = [
    {
        "id": "l005",
        "title": "太虚城·地脉守护",
        "desc": "太虚城地脉出现异变，一头上古地灵兽苏醒，需顶尖强者前往镇压。",
        "type": "combat",
        "req": {"min_realm": "结丹期初期", "min_stat": {"soul": 9}},
        "enemy": {"name": "上古地灵兽", "power": 3000},
        "rewards": {"spirit_stones": 25000, "reputation": 180, "lifespan": 40,
                    "technique": "天罗地网步", "stat_bonus": {"soul": 2}},
    },
    {
        "id": "l006",
        "title": "幽冥海·深渊探索",
        "desc": "幽冥海最深处发现一处上古秘境入口，需极强神识才能感知其中奥秘。",
        "type": "gather",
        "req": {"min_realm": "结丹期中期", "min_stat": {"soul": 9}},
        "location": "幽冥海",
        "rewards": {"spirit_stones": 18000, "reputation": 130, "lifespan": 35,
                    "technique": "九转玄功", "stat_bonus": {"soul": 2, "comprehension": 1}},
    },
    {
        "id": "l007",
        "title": "虚空裂缝·时空傀儡首领",
        "desc": "虚空裂缝深处出现时空傀儡首领，其体内封存着上古修士的毕生感悟。",
        "type": "combat",
        "req": {"min_realm": "元婴期初期", "min_stat": {"comprehension": 9}},
        "enemy": {"name": "时空傀儡首领", "power": 10000},
        "rewards": {"spirit_stones": 60000, "reputation": 350, "lifespan": 120,
                    "technique": "混元一气功", "stat_bonus": {"comprehension": 3, "soul": 2}},
    },
    {
        "id": "l008",
        "title": "昆仑秘境·上古神兽",
        "desc": "昆仑秘境最深处沉睡的上古神兽苏醒，其身上蕴含着天地至理，击败可获天道感悟。",
        "type": "combat",
        "req": {"min_realm": "元婴期中期", "min_stat": {"physique": 10, "bone": 9}},
        "enemy": {"name": "上古神兽", "power": 15000},
        "rewards": {"spirit_stones": 80000, "reputation": 500, "lifespan": 200,
                    "technique": "逍遥游", "stat_bonus": {"physique": 3, "bone": 2, "comprehension": 2}},
    },
    {
        "id": "l009",
        "title": "古战场·战神遗志",
        "desc": "古战场深处出现上古战神的残留意志，凝聚成实体，挑战者可继承其战道传承。",
        "type": "combat",
        "req": {"min_realm": "结丹期后期", "min_stat": {"physique": 9, "bone": 8}},
        "enemy": {"name": "战神意志", "power": 6000},
        "rewards": {"spirit_stones": 35000, "reputation": 250, "lifespan": 60,
                    "technique": "破军刀法", "stat_bonus": {"physique": 3, "bone": 2}},
    },
    {
        "id": "l010",
        "title": "天雷谷·雷劫洗礼",
        "desc": "天雷谷核心出现千年一遇的天雷汇聚，以肉身承受雷劫可获得极大淬炼。",
        "type": "gather",
        "req": {"min_realm": "结丹期初期", "min_stat": {"physique": 8, "bone": 9}},
        "location": "天雷谷",
        "rewards": {"spirit_stones": 22000, "reputation": 160, "lifespan": 45,
                    "technique": "罡气护体", "stat_bonus": {"physique": 2, "bone": 3}},
    },
    {
        "id": "l001",
        "title": "昆仑秘境·封印守护者",
        "desc": "昆仑秘境深处的上古封印出现裂缝，一头远古凶兽即将破封而出，需强者前往镇压。",
        "type": "combat",
        "req": {"min_realm": "结丹期初期", "min_stat": {"comprehension": 8, "physique": 8}},
        "enemy": {"name": "远古凶兽", "power": 2000},
        "rewards": {"spirit_stones": 20000, "reputation": 150, "lifespan": 30,
                    "technique": "混元一气功", "stat_bonus": {"comprehension": 2}},
    },
    {
        "id": "l002",
        "title": "虚空裂缝·时空乱流",
        "desc": "虚空裂缝中出现时空乱流，上古传承随之浮现，只有最强者才能取走。",
        "type": "combat",
        "req": {"min_realm": "元婴期初期"},
        "enemy": {"name": "时空傀儡", "power": 8000},
        "rewards": {"spirit_stones": 50000, "reputation": 300, "lifespan": 100,
                    "technique": "逍遥游", "stat_bonus": {"soul": 3, "comprehension": 2}},
    },
    {
        "id": "l003",
        "title": "天雷谷·渡劫试炼",
        "desc": "天雷谷中有一道上古雷劫试炼，通过者可获得雷属天道感悟，修为大进。",
        "type": "gather",
        "req": {"min_realm": "结丹期中期", "min_stat": {"bone": 8}},
        "location": "天雷谷",
        "rewards": {"spirit_stones": 15000, "reputation": 120, "cultivation": 2000,
                    "technique": "九转玄功", "stat_bonus": {"bone": 2}},
    },
    {
        "id": "l004",
        "title": "万妖岭·妖王讨伐",
        "desc": "万妖岭深处的妖王苏醒，率领妖兽大军威胁周边城市，各大宗门联合悬赏。",
        "type": "combat",
        "req": {"min_realm": "结丹期后期", "min_stat": {"physique": 9}},
        "enemy": {"name": "万妖岭妖王", "power": 5000},
        "rewards": {"spirit_stones": 30000, "reputation": 200, "lifespan": 50,
                    "technique": "万剑归宗", "stat_bonus": {"physique": 2, "bone": 1}},
    },
]
